version: '3.4'
services:
  openagent:
    image: rss3/openagent:latest
    container_name: openagent
    ports:
      - "18000:8000"
    env_file:
      - .env
    depends_on:
      - vector_db
    networks:
      - openagent-network

  vector_db:
    image: pgvector/pgvector:pg16
    container_name: vec_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openagent
    ports:
      - "15432:5432"
    volumes:
      - vector_data:/var/lib/postgresql/data
    networks:
      - openagent-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "21434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - openagent-network

volumes:
  vector_data:
  ollama_data:
networks:
  openagent-network:
    external: false
