version: '3.4'
services:
  vec_db:
    image: pgvector/pgvector:pg16
    container_name: vec_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vec
    ports:
      - "5434:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data


volumes:
  pgvector_data:
