version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vec_db
      - ollama_init
    networks:
      - openagent-network

  vec_db:
    image: pgvector/pgvector:pg16
    container_name: vec_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vec
    ports:
      - "5432:5432"
    volumes:
      - vector_data:/var/lib/postgresql/data
    networks:
      - openagent-network

  ollama:
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - openagent-network

  ollama_init:
    image: curlimages/curl:latest
    container_name: ollama_init
    depends_on:
      - ollama
    entrypoint: [ "/bin/sh", "-c", "curl -X POST -H 'Content-Type: application/json' -d '{\"name\": \"${MODEL_NAME}\"}' http://ollama:11434/api/pull" ]
    env_file:
      - .env
    networks:
      - openagent-network

volumes:
  vector_data:
  ollama_data:
networks:
  openagent-network:
    external: false
