name: backend code quality

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'prod'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pip install flake8 mypy pydantic types-requests types-redis ruff
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --config=backend/.pre-commit-config.yaml --files ./backend/*